export const firstNames = [
  'Alexandre',
  'Camille',
  'Lucas',
  'Emma',
  'Hugo',
  'Léa',
  'Louis',
  'Chloé',
  'Arthur',
  'Manon',
  'Nathan',
  'Sarah',
  'Maxime',
  'Laura',
  'Tom',
  'Julie',
  'Antoine',
  'Marine',
  'Théo',
  'Charlotte',
  'Paul',
  'Mathilde',
  'Victor',
  'Pauline',
  'Gabriel',
  'Alice',
  'Raphaël',
  'Inès',
  'Adam',
  'Anaïs',
  'Jules',
  'Lucie',
  'Ethan',
  'Margaux',
  'Noah',
  'Clara',
  'Matteo',
  'Lisa',
  'Benjamin',
  'Zoé',
  'Enzo',
  'Louise',
  'Clément',
  'Eva',
  'Samuel',
  'Romane',
  'Simon',
  'Jade',
  'Baptiste',
  'Elise',
]

export const lastNames = [
  'Lefebvre',
  'Leroy',
  'Moreau',
  'Simon',
  'Laurent',
  'Lefèvre',
  'Michel',
  'Garcia',
  'David',
  'Bertrand',
  'Roux',
  'Vincent',
  'Fournier',
  'Morel',
  'Girard',
  'André',
  'Mercier',
  'Dupuis',
  'Lambert',
  'Bonnet',
  'François',
  'Martinez',
  'Legrand',
  'Garnier',
  'Faure',
  'Rousseau',
  'Blanc',
  'Guerin',
  'Muller',
  'Henry',
  'Roussel',
  'Nicolas',
  'Perrin',
  'Morin',
  'Mathieu',
  'Clement',
  'Gauthier',
  'Dumont',
  'Lopez',
  'Fontaine',
  'Chevalier',
  'Robin',
  'Masson',
  'Sanchez',
  'Gerard',
  'Nguyen',
  'Boyer',
  'Denis',
  'Lemaire',
  'Durand',
]

export const teachersData = [
  { email: 'marie.dupont@school.com', name: 'Marie', lastName: 'Dupont' },
  { email: 'pierre.martin@school.com', name: 'Pierre', lastName: 'Martin' },
  { email: 'sophie.bernard@school.com', name: 'Sophie', lastName: 'Bernard' },
  { email: 'luc.petit@school.com', name: 'Luc', lastName: 'Petit' },
  { email: 'claire.robert@school.com', name: 'Claire', lastName: 'Robert' },
  { email: 'thomas.richard@school.com', name: 'Thomas', lastName: 'Richard' },
  { email: 'julie.dubois@school.com', name: 'Julie', lastName: 'Dubois' },
  { email: 'marc.moreau@school.com', name: 'Marc', lastName: 'Moreau' },
  { email: 'isabelle.laurent@school.com', name: 'Isabelle', lastName: 'Laurent' },
  { email: 'nicolas.simon@school.com', name: 'Nicolas', lastName: 'Simon' },
]

export const classNames = [
  'Alan Turing',
  'Grace Hopper',
  'Ada Lovelace',
  'Dennis Ritchie',
  'Linus Torvalds',
  'Tim Berners-Lee',
  'Steve Jobs',
  'Bill Gates',
  'Margaret Hamilton',
  'John von Neumann',
  'Claude Shannon',
  'Donald Knuth',
  'Bjarne Stroustrup',
  'Guido van Rossum',
  'James Gosling',
]

export const examTitles = [
  'Algorithmique et programmation',
  'Bases de données relationnelles',
  'Développement Web Frontend',
  'Développement Web Backend',
  'Sécurité informatique',
  'Réseaux et infrastructures',
  'Gestion de projet Agile',
  'Architecture logicielle',
  'DevOps et intégration continue',
  'Cloud Computing',
  'Intelligence Artificielle',
  'Développement Mobile',
  "Systèmes d'exploitation",
  'UX/UI Design',
  "Mathématiques pour l'informatique",
]

export const qcmQuestions = [
  {
    title: "Qu'est-ce qu'une base de données relationnelle ?",
    answers: [
      { answer: 'Un système de gestion de fichiers', isCorrect: false },
      { answer: 'Un système basé sur des tables liées entre elles', isCorrect: true },
      { answer: 'Un langage de programmation', isCorrect: false },
      { answer: 'Un protocole réseau', isCorrect: false },
    ],
  },
  {
    title: 'Quel est le rôle du CSS ?',
    answers: [
      { answer: 'Gérer la base de données', isCorrect: false },
      { answer: 'Styliser les pages web', isCorrect: true },
      { answer: 'Créer des animations 3D', isCorrect: false },
      { answer: 'Compiler le code', isCorrect: false },
    ],
  },
  {
    title: 'Quelle méthode HTTP est utilisée pour créer une ressource ?',
    answers: [
      { answer: 'GET', isCorrect: false },
      { answer: 'POST', isCorrect: true },
      { answer: 'DELETE', isCorrect: false },
      { answer: 'UPDATE', isCorrect: false },
    ],
  },
  {
    title: "Qu'est-ce que Git ?",
    answers: [
      { answer: 'Un langage de programmation', isCorrect: false },
      { answer: 'Un système de gestion de versions', isCorrect: true },
      { answer: 'Un framework JavaScript', isCorrect: false },
      { answer: 'Un serveur web', isCorrect: false },
    ],
  },
  {
    title: 'Quelle est la complexité temporelle de la recherche binaire ?',
    answers: [
      { answer: 'O(n)', isCorrect: false },
      { answer: 'O(log n)', isCorrect: true },
      { answer: 'O(n²)', isCorrect: false },
      { answer: 'O(1)', isCorrect: false },
    ],
  },
]

export const multipleQcmQuestions = [
  {
    title: 'Quels sont les principes SOLID ? (Plusieurs réponses)',
    answers: [
      { answer: 'Single Responsibility', isCorrect: true },
      { answer: 'Open/Closed', isCorrect: true },
      { answer: 'Multiple Inheritance', isCorrect: false },
      { answer: 'Liskov Substitution', isCorrect: true },
    ],
  },
  {
    title: 'Quels langages sont typés statiquement ?',
    answers: [
      { answer: 'JavaScript', isCorrect: false },
      { answer: 'TypeScript', isCorrect: true },
      { answer: 'Python', isCorrect: false },
      { answer: 'Java', isCorrect: true },
    ],
  },
]

export const customQuestions = [
  { title: 'Expliquez le concept de polymorphisme en programmation orientée objet.' },
  { title: 'Décrivez les différences entre SQL et NoSQL.' },
  { title: "Qu'est-ce que le Design Pattern MVC et comment fonctionne-t-il ?" },
  { title: "Expliquez le principe de l'injection de dépendances." },
  { title: "Qu'est-ce que REST et quels sont ses principes fondamentaux ?" },
]
